name: chatverse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9

  # Firebase core packages
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_messaging: ^15.2.9

  # Google sign-in
  google_sign_in: ^7.1.0

  # UI/UX
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  material_design_icons_flutter: ^7.0.7296

  # Media handling
  image_picker: ^1.0.7
  file_picker: ^10.2.0
  flutter_sound: ^9.2.13
  cached_network_image: ^3.3.1

  # Notifications
  flutter_local_notifications: ^19.3.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.2

  # Flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- ADD THIS SECTION TO EXPLICITLY DECLARE the desktop plugin classes ---
  plugin:
    platforms:
      macos:
        pluginClass: FilePickerPlugin
      linux:
        pluginClass: FilePickerLinuxPlugin
      windows:
        pluginClass: FilePickerWindowsPlugin
